# Site settings

title: Yet Another Linux Nerd # Title of your site

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://linux-nerd.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     0livier  # Replace this with your Twitter username
github_username:      0livier  # Replace this with your GitHub username
linkedin_username:    0livier  # Replace this with your LinkedIn username

# Build settings
markdown: kramdown

permalink: /blog/:title

gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-sitemap
 - jemoji
 - jekyll-mentions

paginate: 5
highlighter: pygments

